### ISSUE TITLE
Discord message gets messed up when someone is mentioned/quoted

### ISSUE THREAD

**Issue by Brikaa** [projectunic0rn/pub-workspace#65]
![image](https://user-images.githubusercontent.com/40431124/94949663-95a98680-04e1-11eb-8cda-b776a091be24.png)
The first message shows what happens when someone is quoted, and the second shows what happens when someone is mentioned.

**Comment by roymoran** [comment]
This is related to how I transform the text before sending the message to each platform. Thanks for raising this @Brikaa.

**Comment by roymoran** [comment]
closing this issue since it was resolved by the PR.
